[project]
name = "tandem"
version = "0.1.0"
description = "Приложение для учета и контроля расхода оборотных средств."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "Igor Mogilin", email = "endless8space@gmail.com"},
    {name = "Anastasia Dekapolceva", email = "deka0665@gmail.com"},
]
license = {text = "MIT"}
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "fastapi>=0.129.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.0",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.46",
    "uvicorn[standard]>=0.41.0",
    "strenum>=0.4.15",
    "psycopg2-binary>=2.9.11",
]

[tool.uv]
default-groups = ["dev"]

[dependency-groups]
dev = [
    "pre-commit>=3.6.0",
    "ruff>=0.1.0",
    "mypy>=1.8.0",
    "pytest>=7.4.0",
    "pytest-asyncio>=0.23.0",
]

[tool.ruff]
line-length = 120
target-version = "py311"
exclude = [".venv", ".git", "migrations/versions"]

[tool.ruff.lint]
select = ["E", "E501", "F", "I", "B", "UP", "ANN"]
ignore = ["ANN101", "ANN102"]

[tool.ruff.lint.isort]
known-first-party = ["common", "models", "src"]
known-third-party = ["sqlalchemy", "alembic", "fastapi", "pydantic", "asyncpg", "strenum"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "src.db.*"
disable_error_code = ["arg-type"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
asyncio_mode = "auto"

[tool.ruff.lint.per-file-ignores]
"src/migrations/versions/*.py" = ["UP007"]
