"""create tables

Revision ID: f4c7223e0c61
Revises: 400d5da7dec3
Create Date: 2026-03-02 23:13:44.565819

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4c7223e0c61"
down_revision: Union[str, Sequence[str], None] = "400d5da7dec3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(as_uuid=False), server_default=sa.text("uuid_generate_v7()"), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False, comment="Имя пользователя"),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False, comment="Telegram ID пользователя"),
        sa.Column(
            "balance",
            sa.Numeric(precision=10, scale=2),
            server_default="0.00",
            nullable=False,
            comment="Доля пользователя в общем фонде (сумма всех начислений)",
        ),
        sa.Column(
            "duty",
            sa.Numeric(precision=10, scale=2),
            server_default="0.00",
            nullable=False,
            comment="Долг пользователя в общий фонд",
        ),
        sa.Column(
            "registered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время добавления пользователя в базу(регистрации)",
        ),
        sa.Column(
            "role",
            sa.Enum("SUPERADMIN", "ADMIN", "AUDITOR", "ALIEN", name="userrole", native_enum=False),
            server_default="ALIEN",
            nullable=False,
            comment="Роль пользователя, определяющая его возможности",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Флаг активности пользователя"),
        sa.CheckConstraint("balance >= 0", name="check_balance_non_negative"),
        sa.CheckConstraint("duty >= 0", name="check_duty_non_negative"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_table(
        "fund_operations",
        sa.Column("id", sa.UUID(as_uuid=False), server_default=sa.text("uuid_generate_v7()"), nullable=False),
        sa.Column(
            "operation_type",
            sa.Enum("INCOMING", "OUTGOING", "REJECTED", name="operationtype", native_enum=False),
            nullable=False,
            comment="Тип операции со средствами фонда",
        ),
        sa.Column(
            "payday",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата выполнения транзакции или ее попытки",
        ),
        sa.Column(
            "payer_id",
            sa.UUID(as_uuid=False),
            nullable=False,
            comment="Ссылка на ID пользователя, сделавшего транзакцию",
        ),
        sa.Column(
            "amount",
            sa.Numeric(precision=10, scale=2),
            server_default="0.00",
            nullable=False,
            comment="Сумма транзакции",
        ),
        sa.Column("operation_text", sa.String(length=500), nullable=True, comment="Комментарий к транзакции"),
        sa.CheckConstraint("amount >= 0", name="check_amount_non_negative"),
        sa.ForeignKeyConstraint(["payer_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fund_operations")
    op.drop_table("user")
    # ### end Alembic commands ###
